Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -12,31 +12,69 @@ permissions:
 
 jobs:
   build:
-    name: Build APK
+    name: Build Android APK
     runs-on: ubuntu-latest
 
     steps:
+
       - name: Checkout Source
         uses: actions/checkout@v4
 
-      - name: Set up JDK 21
+
+      - name: Show Project Structure
+        run: |
+          echo "Current directory:"
+          pwd
+
+          echo "Root files:"
+          ls -la
+
+          echo "Searching gradlew:"
+          find . -name gradlew -type f
+
+
+      - name: Setup JDK 21
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: '21'
-          cache: gradle
+
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
 
-      - name: Grant Execute Permission
-        run: chmod +x gradlew
+
+      - name: Find Gradle Wrapper
+        id: gradle
+        shell: bash
+        run: |
+          GRADLE_PATH=$(find . -name gradlew -type f | head -n 1)
+
+          if [ -z "$GRADLE_PATH" ]; then
+            echo "ERROR: gradlew not found"
+            exit 1
+          fi
+
+          echo "Found: $GRADLE_PATH"
+
+          chmod +x "$GRADLE_PATH"
+
+          DIR=$(dirname "$GRADLE_PATH")
+
+          echo "dir=$DIR" >> $GITHUB_OUTPUT
+
 
       - name: Build Debug APK
-        run: ./gradlew assembleDebug
+        run: |
+          cd "${{ steps.gradle.outputs.dir }}"
+          ./gradlew assembleDebug
+
 
       - name: Build Release APK
-        run: ./gradlew assembleRelease
+        run: |
+          cd "${{ steps.gradle.outputs.dir }}"
+          ./gradlew assembleRelease
+
 
       - name: Upload Debug APK
         uses: actions/upload-artifact@v4
@@ -45,6 +83,7 @@ jobs:
           path: |
             **/build/outputs/apk/debug/*.apk
 
+
       - name: Upload Release APK
         uses: actions/upload-artifact@v4
         with:
@@ -52,10 +91,11 @@ jobs:
           path: |
             **/build/outputs/apk/release/*.apk
 
-      - name: Upload Mapping Files
+
+      - name: Upload Build Reports
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: Mapping
+          name: Build-Reports
           path: |
-            **/build/outputs/mapping/**
+            **/build/reports/**
